#!/bin/bash -l
#SBATCH --job-name=hunter_rabbit
#SBATCH --output=output.slurm

#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=10000mb
#SBATCH --mail-type=START,END,FAIL,REQUEUE,STAGE_OUT
#SBATCH --mail-user=qhv200@nyu.edu

#source activate /scratch/qhv200/conda_envs/pytorch1_cpu_py36
source activate /scratch/qhv200/conda3-envs/pytorch1_cpu_py36
cd /scratch/qhv200/kenny_drl/master

OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python policy_gradient.py --save_policy